### ISSUE TITLE
Update needs to be performed twice, after update prompt and download

### ISSUE THREAD

**Issue by RobJackson28** [chgibb/PHAT#389]
Tried updating from v0.0.14 (win32) to v0.0.15 after prompt, download, and restarting software (after 5 min). Still showed v0.0.14 and prompted for update again. After the second time it appears to be properly updated to v0.0.15.

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.1 to v0.1.10beta.2

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.2 to v0.1.10beta.3

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.3 to v0.1.10beta.4

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.4 to v0.1.10beta.5

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.5 to v0.1.10beta.6

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1-beta.7 to v0.1.1 (stable)

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.1 (stable) to 0.1.2-beta.1

**Comment by RobJackson28** [comment]
Also occurred when updating win32 installed v0.1.1 (stable) to 0.1.2-beta.1

**Comment by RobJackson28** [comment]
Occurred twice updating win32 installed v0.1.2-beta.1 to 0.1.3-beta.1

**Comment by RobJackson28** [comment]
Occurred again when updating win32 portable v0.1.5-beta.1 to v0.1.5 (stable). No problems with the installed version.

**Comment by RobJackson28** [comment]
Slightly different error than I've encountered in the past, when updating win32 portable v0.3.0-beta.1 to v0.4.0-beta.1, where the pop-up did initiate, but then crashed a few seconds after. In the update error log:

Message :The process cannot access the file 'C:\Users\Rob\Desktop\phat-win32-x64-portable\blink_image_resources_200_percent.pak' because it is being used by another process.<br/>
StackTrace :   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry(String destDir, TarEntry entry)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
   at phat.procMain.Main(String[] args)
Date :15-Sep-2017 15:50:47

**Comment by RobJackson28** [comment]
The same problem as 15 Sep 2017 (updating pop-up initiates after the download, but then crashes after a few seconds) occurred two times when updating win32 portable v0.4.0-beta.1 to v0.4.1-beta.1. Error log:

-----------------------------------------------------------------------------

Message :The requested operation cannot be performed on a file with a user-mapped section open.
<br/>
StackTrace :   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry(String destDir, TarEntry entry)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
   at phat.procMain.Main(String[] args)
Date :19-Sep-2017 09:21:29

-----------------------------------------------------------------------------

Message :The requested operation cannot be performed on a file with a user-mapped section open.
<br/>
StackTrace :   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry(String destDir, TarEntry entry)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
   at phat.procMain.Main(String[] args)
Date :19-Sep-2017 09:22:26

-----------------------------------------------------------------------------

**Comment by RobJackson28** [comment]
The same problem as earlier today (updating pop-up initiates after the download, but then crashes after a few seconds) occurred once when updating win32 installed v0.4.0-beta.1 to v0.4.1-beta.1.

**Comment by RobJackson28** [comment]
Similar problem occurred when updating win32 portable v0.7.4-beta.1 to v0.7.5-beta.1: first download spontaneously crashed, second download got mid-way and then prompted a .NET framework install, but did not continue automatically afterward. Third download proceeded successfully and update proceed successfully.

**Comment by RobJackson28** [comment]
No issues with update from win32 portable 0.7.5-beta.1 to 0.7.6-beta.1
